services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5431:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
